name: Release
on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-22-arm64-2-core
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Make
        run: |
          make all
      - uses: ncipollo/release-action@v1
        with:
          artifacts: build/anti-virus.zip
          allowUpdates: true
